### ISSUE TITLE
Missing licence on rubygems.org and in gemspec file

### ISSUE THREAD

**Issue by peterjc** [bioruby/bioruby#101]
On https://rubygems.org/gems/bio the BioRuby licence is listed as N/A, but according to your ``README.rdoc`` it uses "The Ruby License".

As per http://guides.rubygems.org/specification-reference/#license= and http://spdx.org/licenses/ please update``bioruby.gemspec.erb`` and ``bioruby.gemspec`` to include the line:
```
      s.license = "Ruby"
```

(I'd do this as a pull request, but I'm not familiar with rake etc)

**Comment by ngoto** [comment]
Thank you. Committed with 5ea39188ac3cc2609397b2d8864a2019ea6b93d2
