### ISSUE TITLE
Bioruby site is down!

### ISSUE THREAD

**Issue by MatthewRalston** [bioruby/bioruby#108]
http://isup.me/bioruby.org

**Comment by ngoto** [comment]
*.open-bio.org server is down now. Currently, please use http://bioruby.github.io/

**Comment by ngoto** [comment]
http://bioruby.org is restored by using the GitHub Pages, though Wiki contents are missing.
http://bioruby.open-bio.org/ will be redirected to http://bioruby.org

**Comment by Seraff** [comment]
Is Wiki going to be fixed?

**Comment by MatthewRalston** [comment]
^

**Comment by ngoto** [comment]
Wiki is now migrated to https://github.com/bioruby/documents/wiki

The pages are converted from MediaWiki to Markdown by using https://github.com/philipashlock/mediawiki-to-markdown with pango. After that, small custom filters are used to adjust links.

Thank you for reporting. We're greatly encouraged by the above messages!

**Comment by ngoto** [comment]
Currently, tutorial link is changed to refer to static html on bioruby.org site.

Tutorials, sample codes and other documentation will be updated by using http://github.com/bioruby/documents and http://github.com/bioruby/documents/wiki repositories.

**Comment by Seraff** [comment]
Very good, thank you!
