### ISSUE TITLE
bio-1.5.0/lib/bio/db.rb:267:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by kim612** [bioruby/bioruby#109]
When I opened gbbct229.seq which was in GenBank database, I found an error.
Temporarily, I changed one line in bio-1.5.0/lib/bio/db.rb of my computer.

Line 267:
str.force_encoding('iso-8859-1').encode('utf-8').gsub(/\n([A-Za-z\/\*])/, "\n#{sep}\\1").split(sep)

Please consider this issue.
Thank you.

**Comment by ngoto** [comment]
This does not occur by using our recommended way to read a file.

`$ LANG=en_US.ISO-8859-1 ruby -r bio -e 'Bio::FlatFile.open("gbbct229.seq") { |f| f.each { |e| puts e.entry_id }}'`

For other data source, to avoid the encoding issue, please set string encoding to "ASCII-8BIT" to the input data.

```
  str.force_encoding("ASCII-8BIT")
  entry = Bio::GenBank.new(str)
```

By the way, the following entries are the cause of this issue.

KR002120.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002120.1
KR002121.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002121.1
KR002122.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002122.1
KR002123.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002123.1
KR002124.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002124.1
KR002125.1  http://www.ncbi.nlm.nih.gov/nuccore/KR002125.1

In these entries, the line "            Assembly Method       :: Geneious� v. Geneious� 7.1.2" apparently contains strange characters.
