### ISSUE TITLE
Change base URLs for NCBI services to use https instead of http

### ISSUE THREAD

**Issue by elucify** [bioruby/bioruby#110]
To improve end user security and privacy, and by Federal government mandate OMB memo M-08-023, NCBI will be moving all web services to HTTPS-only by September 30, 2016.

bioruby needs to be updated to use https:// URLs instead of http:// URLs. While we intend to provide redirects for GET and HEAD, POST and other non-safe methods will likely not be redirected; in particular, epost will cease to function over http when we move to https.

For more information:

http://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/
https://https.cio.gov/
subscribe to the utilities-announce mailing list at https://www.ncbi.nlm.nih.gov/mailman/listinfo/utilities-announce

**Comment by elucify** [comment]
The Federal deadline is December 31, but the National Library of Medicine deadline is September 30.

**Comment by elucify** [comment]
Is the official bioruby repo? Is this repo being maintained? I see open PRs from 2013...

**Comment by ngoto** [comment]
Sorry for late response.

I'm planning new release including this change.

**Comment by elucify** [comment]
I'm going to release advice to developers about how to update their applications that use NCBI APIs. For the other language-specific libraries (biojava, etc.), I'm linking to the release that fixes the problem. For the time being, I'll link to this issue. Once there's a release, and a place to download it, I can change the link to point there. You can just contact me when you're ready. Thanks!

**Comment by ngoto** [comment]
fixed with 018c2aff1c7813e7b07362ecc8a25db334c0ae95 and 47ada241ad6f3632dbbd77542befb82500b7195e

**Comment by ngoto** [comment]
BioRuby 1.5.1 will soon be released

**Comment by elucify** [comment]
Checking to see if 1.5.1 is released yet and, if so, where it can be found.

**Comment by ngoto** [comment]
BioRuby 1.5.1 is released just now!

http://bioruby.org/archive/bioruby-1.5.1.tar.gz
https://rubygems.org/gems/bio
