### ISSUE TITLE
Rails 5 eager loading (gem broken in Rails 5+)

### ISSUE THREAD

**Issue by timsaunders** [bioruby/bioruby#116]
I have just upgraded rails application to the latest rails version, which at this time is 5.0.2, which was previously using a rails 3 version. However after the upgrade, in production mode, the gem seems to kill the entire application, since it is trying to load in memory all the .rb files, including the ones in the /bin directory. I then get the following message:

`bin/rails [-s[erver] http://www.ebi.ac.uk/cgi-bin/dbfetch] db id [style] [format]
  server : URL of the BioFetch CGI (default is http://bioruby.org/cgi-bin/biofetch.rb)
      db : database name (embl, genbank, etc.)
      id : entry id
   style : 'raw' or 'html' (default is 'raw')
  format : change the output format ('default', 'fasta', etc.)`

However I am never using the Bio:Fetch feature anywhere in my code, it seems that rails is trying to load the bin/*.rb files which contains the files with no scope/namespace around them. So when rails loads up, with eager_load=true, rails tries to load them, however crashes. For example in biofetch.rb, there is code (line 46 and below), which is not contained that runs this code, however there is an exit 1, which crashes the rails app.

It would be better to scope/namespace these *.rb, so rails doesn't try to load them when the app loads all the *.rb into memory when eager_load = true. Currently there is no way to use this gem when eager load is set for Rails applications > v4+

**Comment by ngoto** [comment]
Could you please check Rails.application.config.eager_load_paths ?

I think this could be a bug of Rails, or inappropriate configuration.

**Comment by ngoto** [comment]
After c89c40c29c3c92f8e548c79d2d0469812355900, all files under bin/ are moved to separate gems ("bio-executables" and "bio-shell" gems) and the bug should go away.
I still believe this bug should be handled by Rails side, though ...
