### ISSUE TITLE
Some classes are not explained in the yard document

### ISSUE THREAD

**Issue by kojix2** [bioruby/bioruby#119]
Hello. I am a beginner of bioruby and bioinformatics.
From a beginner's point of view, bioruby has problems with documentation.

I installed bioruby, launched yard and observed modules and classes.

But bioruby does not have enough documentation.
Even if there are comments in the code, it may not be displayed by yard.
This is disappointing.

Perhaps "bioruby" may be a tool for experts with sufficient knowledge of bioinformatics.
But I like tools that are easy to understand.

**Comment by ngoto** [comment]
I commented at https://github.com/bioruby/bioruby/pull/120#issuecomment-385375438

**Comment by ngoto** [comment]
AAindex problem was fixed by commit 02a964241b79e2307d0a00473427ea6bc2ea6932
