### ISSUE TITLE
Is there a way to get KEGG pathway images?

### ISSUE THREAD

**Issue by kojix2** [bioruby/bioruby#129]
Is there a way to get KEGG pathway images?
I want to generate coloured image of the pathway. 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2951089/

**Comment by kojix2** [comment]
Pathview, an R package, provides the following shell script and web service:
`pathview.sh`
https://pathview.uncc.edu/api_tutorial

You can generate colored KEGG pathway images by calling this script from Ruby.

**Comment by ngoto** [comment]
Thanks!

It seems that scraping from https://www.genome.jp/kegg/tool/map_pathway3.html could also achieve this.
