### ISSUE TITLE
Issue about no file found 

### ISSUE THREAD

**Issue by Danissss** [bioruby/bioruby#131]
I am trying to use bioruby in rails on ruby, and when I tried to do bio:blast:new
```
blaster = Bio::Blast.local( program, "#{Rails.root}/index/blast/#{database}", blast_options)
report = blaster.query(@sequence.seq)
```
I got this error `No such file or directory - blastall`

My #{database} contain `.nhr`, `.nin`,`.nsq` files which generated from ncbi standard tool.

Thanks for any help.

**Comment by ktym** [comment]
My guess is that your Rails app could not find `blastall` command in the PATH.

**Comment by Danissss** [comment]
Hi @ktym , are you suggesting my NCBI program is not properly set? Could I ask how to set the `blastall` to PATH? Thank you!

**Comment by ktym** [comment]
It might depend on how you deploy your Rails app and I'm not following recent Rails conventions but you can try to add a line something like
ENV['PATH'] += ':/path/to/blastall/installed/directory'
in your app (e.g., config/application.rb maybe?) and see if it works.

**Comment by Danissss** [comment]
I installed the ncbi blast+ program from ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/, and I couldn't find `blastall` program. I found that `blastall` is the legacy program. I wondering does BioRuby still require `blastall`?

**Comment by ktym** [comment]
Ah yes, good point. Surprisingly, it seems that Bio::Blast is not updated to support `blast+` even in the BioRuby 2.0.0 release!

Easiest (ad hoc) hack would be to use the `legacy_blast.pl` script bundled with the `blast+` distribution and modify the code for command line generation in BioRuby's `lib/bio/appl/blast.rb` as follows...

```
module Bio
  class Blast
    def make_command_line
      path = "/path/to/ncbi-blast-2.9.0+/bin"  # CHANGE ME
      cmd = make_command_line_options
      cmd.unshift @blastall
      cmd.unshift "#{path}/legacy_blast.pl"    # ADDED
      cmd.push "--path"                        # ADDED
      cmd.push path                            # ADDED
      cmd
    end
  end
end

program = "blastn"
blast_options = "-m 8"

blaster = Bio::Blast.local(program, "#{Rails.root}/index/blast/#{database}", blast_options)
report = blaster.query(@sequence.seq)
```

Of course, re-writing the BioRuby core to natively support `blast+` is the way to go in long-term though (depending on Perl just to run the blast in Ruby makes no sense;).

**Comment by Danissss** [comment]
@ktym  Thank you for the fix. It works. Just reminder that `legacy_blast.pl` use default `/usr/bin` for blast program path, which may need to be modified a little bit to match the new blast program location.

**Comment by ktym** [comment]
To my understanding, you can use `legacy_blast.pl` with the `--path /path/to/2.9.0+/bin` option to change from the default `/usr/bin` as in the previous code.

```
      cmd.push "--path"                        # ADDED
      cmd.push path                            # ADDED
```

**Comment by Danissss** [comment]
@ktym Hi, I am wondering when the new blast+ program can be integrated? Do you guys have any plan on that? If not, I guess I can offer some help.

**Comment by ktym** [comment]
@Danissss I'm afraid that I will not be able to work on this for a while, so it would be great if you could contribute support for blast+ (either as a patch to the bioruby-core or as a biogems package, maybe).

**Comment by Danissss** [comment]
@ktym Yes, I would like to help. However, I never contribute to an open source before. Could you give me some suggestions? I assume pull request first (fix) and push?
