### ISSUE TITLE
required libraries not loaded 

### ISSUE THREAD

**Issue by markwilkinson** [bioruby/bioruby#135]
Hi BioRubyists!

the following code unexpectedly doesn't work:

require 'bio'
s = Bio::Sequence.auto("ACGTCGATCGTAGCTAGTGCTAGCGTAGCTGACTGACG")
s.output(:embl)

it returns:  NameError (uninitialized constant Bio::Sequence::Format::INSDFeatureHelper::Date)

I can solve this by also:   require 'bio/db/embl/embl'   but I feel like this should not be necessary...?

is this a bug, or a feature? :-)

Cheers!
Mark

**Comment by ngoto** [comment]
It seems it is a bug. Some `require` or `autoload` lines should be added in some files.

Thanks. I'm sorry for late response.
