### ISSUE TITLE
Request for technical discussions feature on this repository

### ISSUE THREAD

**Issue by hwpplayer1** [bioruby/bioruby#136]
Hi I want to get involved and I think that it should be a quick solution if we have a Discussions section on this repository

Thanks for all your contributions

**Comment by ngoto** [comment]
Is the section provided by GitHub?

**Comment by hwpplayer1** [comment]
Yes by GitHub @ngoto

**Comment by ngoto** [comment]
How to set up? Is there documentation in GitHub Docs (https://docs.github.com/ )?

**Comment by hwpplayer1** [comment]
@ngoto Please go to your repository settings and see there "Discussions"

**Comment by ngoto** [comment]
It is enabled now. Thanks very much!
