### ISSUE TITLE
On Ruby 3.0, methods in a subclass of String return String instead of the subclass instance

### ISSUE THREAD

**Issue by ngoto** [bioruby/bioruby#137]
According to News for Ruby 3.0 (https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md ), many methods return or yield String instances instead of subclass instances when called on subclass instances. This change severely affects Bio::String classes.

Simple example:
<pre>
irb(main):001:1* s = Bio::Sequence::NA.new("acgt")
=> "acgt"
irb(main):002:0> s.class
=> Bio::Sequence::NA
irb(main):003:0* s2 = s * 2
=> "acgtacgt"
irb(main):004:0> s2.class
=> String
</pre>

On Ruby 2.7 or earlier, Bio::Sequence::NA was shown.

**Comment by rubyFeedback** [comment]
I think for users it would be more useful if a special class, such as NA,
is returned. .to_s / .to_str will yield the desired string behaviour anyway
so it should be fine. That's just my opinion though. Probably keeps 
backwards behaviour as well.

**Comment by nileshpatra** [comment]
@ngoto @ktym any news on this? Now ruby 3.0 has become the default in debian, and it's a bit urgent for us.
Thanks for your work.

**Comment by ngoto** [comment]
Thanks let us know. I'll soon fix this

**Comment by nileshpatra** [comment]
@ngoto Many thanks for working on this, awesome! Can I ask you to please tag a new release/tag for this one?
It makes it easier for me to pull changes.

**Comment by ngoto** [comment]
bioruby 2.0.3 will be released very soon

**Comment by ngoto** [comment]
bioruby 2.0.3 is released, including this fix

**Comment by nileshpatra** [comment]
Awesome, thank you very much! :-)
