### ISSUE TITLE
Fix Gem::Specification dep warnings

### ISSUE THREAD

**Issue by jaysonvirissimo** [bioruby/bioruby#138]
On Ruby 2.6.2, from the top level directory, running `bundle install && rake test` results in the following warnings:
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from (eval):583.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from (eval):580.
```

**Comment by ngoto** [comment]
`Gem::Specification#has_rdoc=` have been deprecated and RDoc have been always generated regardless of the value since RubyGems 1.3.3 in 2009.
https://blog.rubygems.org/2009/05/04/1.3.3-released.html
So, the line `s.has_rdoc = true` will be removed.
