### ISSUE TITLE
bioruby shell seems broken

### ISSUE THREAD

**Issue by markwilkinson** [bioruby/bioruby#146]
Starts correctly exactly once, and after that...

$ bioruby
Loading config (/home/osboxes/.bioruby/shell/session/config) ... done
irb: warn: can't alias ls from irb_ls.
Loading object (/home/osboxes/.bioruby/shell/session/object) ... done
Loading history (/home/osboxes/.bioruby/shell/session/history) ... /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/lib/bio/shell/core.rb:400:in `block i
ror)
Did you mean?  Reline
               Bio::MEDLINE
	from /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/lib/bio/shell/core.rb:398:in `each'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/lib/bio/shell/core.rb:398:in `load_history_file'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/lib/bio/shell/core.rb:391:in `load_history'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/lib/bio/shell/core.rb:128:in `load_session'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/gems/bio-shell-1.0.0/bin/bioruby:24:in `<top (required)>'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/bin/bioruby:25:in `load'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/bin/bioruby:25:in `<main>'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /home/osboxes/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by ngoto** [comment]
related issue (with pull request): https://github.com/bioruby/bioruby-shell/issues/2

As described in the above issue, irb bundled with Ruby 2.7 or later is drastically changed, and the proposed fix might conflict with the recent new features of irb. I'll soon investigate more.

**Comment by ngoto** [comment]
New version of bio-shell (bio-shell-1.0.1.gem) is released.
Running on Ruby 3.0.x seems fine with bio-shell 1.0.1 and bio 2.0.3 gems.
