### ISSUE TITLE
Bug in UniProtKB class with ft field

### ISSUE THREAD

**Issue by seoanezonjic** [bioruby/bioruby#147]
Hi
I'm processing the file uniprot_sprot_rodents.dat.gz from uniprot and when I want to access to FT field of a record, this error raises:

bio-2.0.3/lib/bio/db/embl/uniprotkb.rb:1256:in `rescue in ft': Invalid FT Lines(Error: start/end position must be a positive integer) in 1433B_MOUSE

The record causing the error is shown and inspecting it I think that the following lines cause the error:

FT   MOD_RES         Q9CQV8-2:1
FT                   /note="N-acetylmethionine"
FT                   /evidence="ECO:0000305"

It seems that the fields FROM/TO are the values Q9CQV8-2/1 and the Q9CQV8-2 id is not expected. I guess that modify the code to take into account this specific situation could be a mess. Would be possible modify the FT parser to ignore these cases? In this way I could use the parser without the problems generated by this kind of fields.

Thank you in advance
Pedro Seoane

**Comment by ngoto** [comment]
The UniProtKB FT (and CC) format have been completely changed since UniProt release 2019_11.
https://www.uniprot.org/news/2019/12/18/release#text%5Fft
The new format should be supported.

**Comment by seoanezonjic** [comment]
HI @ngoto 
I tested your new parser and it gives me the following error:
/mnt/home/soft/soft_bio_267/programs/x86_64/rvm/gems/ruby-3.1.2/gems/bio-2.0.4/lib/bio/db/embl/uniprotkb.rb:1317:in `rescue in ft_2019_11_parser': Invalid FT Lines(Error: start/end position must be a positive integer) in 5HT1B_RABIT:,  (RuntimeError)
'FT   CHAIN           1..390
FT                   /note="5-hydroxytryptamine receptor 1B"
FT                   /id="PRO_0000068920"
FT   TOPO_DOM        1..49
FT                   /note="Extracellular"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        50..75
FT                   /note="Helical; Name=1"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        76..84
FT                   /note="Cytoplasmic"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        85..110
FT                   /note="Helical; Name=2"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        111..123
FT                   /note="Extracellular"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        124..145
FT                   /note="Helical; Name=3"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        146..165
FT                   /note="Cytoplasmic"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        166..187
FT                   /note="Helical; Name=4"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        188..205
FT                   /note="Extracellular"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        206..228
FT                   /note="Helical; Name=5"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        229..315
FT                   /note="Cytoplasmic"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        316..336
FT                   /note="Helical; Name=6"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        337..349
FT                   /note="Extracellular"
FT                   /evidence="ECO:0000250"
FT   TRANSMEM        350..371
FT                   /note="Helical; Name=7"
FT                   /evidence="ECO:0000250"
FT   TOPO_DOM        372..390
FT                   /note="Cytoplasmic"
FT                   /evidence="ECO:0000250"
FT   REGION          125..134
FT                   /note="Agonist binding"
FT                   /evidence="ECO:0000250"
FT   REGION          260..282
FT                   /note="Disordered"
FT                   /evidence="ECO:0000256|SAM:MobiDB-lite"
FT   REGION          327..331
FT                   /note="Agonist binding"
FT                   /evidence="ECO:0000250"
FT   MOTIF           146..148
FT                   /note="DRY motif; important for ligand-induced conformation
FT                   changes and signaling"
FT                   /evidence="ECO:0000250"
FT   MOTIF           365..369
FT                   /note="NPxxY motif; important for ligand-induced
FT                   conformation changes and signaling"
FT                   /evidence="ECO:0000250"
FT   SITE            355
FT                   /note="Important for species-specific agonist sensitivity"
FT                   /evidence="ECO:0000250"
FT   LIPID           388
FT                   /note="S-palmitoyl cysteine"
FT                   /evidence="ECO:0000255"
FT   CARBOHYD        24
FT                   /note="N-linked (GlcNAc...) asparagine"
FT                   /evidence="ECO:0000255"
FT   CARBOHYD        32
FT                   /note="N-linked (GlcNAc...) asparagine"
FT                   /evidence="ECO:0000255"
FT   DISULFID        122..199
FT                   /evidence="ECO:0000255|PROSITE-ProRule:PRU00521"
FT   CONFLICT        5
FT                   /note="G -> S (in Ref. 1 and 3)"
FT                   /evidence="ECO:0000305"
FT   CONFLICT        7
FT                   /note="Q -> R (in Ref. 1 and 3)"
FT                   /evidence="ECO:0000305"
FT   CONFLICT        14
FT                   /note="Missing (in Ref. 1 and 3)"
FT                   /evidence="ECO:0000305"
FT   CONFLICT        171
FT                   /note="R -> A (in Ref. 1 and 3)"
FT                   /evidence="ECO:0000305"

Currently, I'm working with the file uniprot_sprot_mammals.dat.gz from the ncbi ftp /pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions. Maybe you could give a run with your parser to check all the possible exceptions.
Thank you in advance.
Pedro Seoane

**Comment by ngoto** [comment]
Thanks for reporting. New release version will soon be released
