### ISSUE TITLE
adding contributions to bioruby

### ISSUE THREAD

**Issue by gauravcodepro** [bioruby/bioruby#148]
dear Toshiaki Katayama, 
thank you for developing bioruby and i am a ruby developer and developed several gems and also currently developing a new bio ruby gem and would like to merge all of these in the bioruby so that it can be installed as a package as compared to the indiviual ruby gems. please kindly let me know as how to contribute to the bioruby.

please find the links to the previous ones and the new ones that i am writing, which includes support for all the pacbio, pacbiohifi, nanopore and all base callers.

> https://github.com/sablokgaurav/sequencing_barcoding_generator
> https://github.com/sablokgaurav/pacbiohifi_motif_scanner
> https://github.com/sablokgaurav/ruby_genome_annotation
> https://github.com/sablokgaurav/miniprot_alignment_ruby_gem 
> https://github.com/sablokgaurav/kmerstring_count_graph

thank you for this information,
gaurav

**Comment by ngoto** [comment]
Thanks, and I'm very sorry I missed the notification and responded too late.

I think it is great to develop them, but we are very sorry that BioRuby (bio.gem) project is currently stopping the integration of new features into bio.gem, because we have been working to split BioRuby (bio.gem) into multiple gem packages, to reduce complexity and maintenance costs. 

Could you please release them as individual gem packages maintained by you?

**Comment by gauravcodepro** [comment]
@ngoto this is great news and i support this as this will allow more readability and integration of the gems. I am developing more of the same along with the other packages. Yes, i have already released some previously and releasing some this month. 

I have a point to ask, does Ruby compiler support the RUST integration as i have seen the rubex integration and it is just like the short notion for the C programming. Let me know if you have some knowledge on the same. 

Thank you.

**Comment by ngoto** [comment]
Magnus ( https://github.com/matsadler/magnus ) may be useful, but I'm sorry I'm not familiar with Rust.

**Comment by gauravcodepro** [comment]
thank you and i am also not coding in RUST at the moment and wanted to ask so as to have that information. Thank you for providing me the link to the corresponding repository.
