### ISSUE TITLE
Tutorial pages don't display correctlty

### ISSUE THREAD

**Issue by aunderwo** [bioruby/bioruby#39]
The tutorial page says to look at the new tutorial at this url

https://raw.github.com/bioruby/bioruby/master/doc/Tutorial.rd.html

This displays as raw text not as html unfortunately :(

**Comment by ngoto** [comment]
http://bioruby.org/doc/Tutorial.rd.html is added.

For documentation, new repository https://github.com/bioruby/documents is created. Tutorials will be updated there.
