### ISSUE TITLE
Bug Report App (on Redmine) is current not starting

### ISSUE THREAD

**Issue by IsmailM** [bioruby/bioruby#98]
This is the link [https://redmine.open-bio.org/projects/bioruby](https://redmine.open-bio.org/projects/bioruby) that is shown on the bioruby home page to report a bug.

Clicking on the link will show that it is down due syntax errors or unavailability of a required module...

**Comment by eronisko** [comment]
FYI, the OBF Redmine is now back up and you should be able to access https://redmine.open-bio.org/projects/bioruby as before.

**Comment by ngoto** [comment]
Thank you. Closing the issue.
